[WTEL-5399]
webitel/cases pull request #2
Opened 2024-12-11 14:46 UTC by Dtsnko

+ filters on search apis

2024-12-12 15:16 UTC, ashalaenko requested changes

2024-12-12 15:16 UTC, ashalaenko commented on internal/store/query_utils.go
> +	if opts.GetSize() > 0 {
ми тут тричі викликаємо одну і ту функцію ж opts.GetSize() , компілятор , можливо зможе це оптимізувати, а може й ні

2024-12-12 15:16 UTC, ashalaenko commented on internal/store/query_utils.go
> +func ResolvePaging[T any](opts model.Pager, items []*T) (next bool) {
ми мутуємо інпут параметр, що можливо не дуже гарна ідея

2024-12-12 15:16 UTC, ashalaenko commented on internal/store/query_utils.go
> +		if len(items) > int(opts.GetSize()-1) {
приклад : 
```
items := []int{1,2,3,4} // len 4
// opts.GetSize() == 1

// len(items) > int(opts.GetSize()-1) --> true , 4 > 0
//  items = items[:opts.GetSize()-1] -->> items = items[:0] -> []
```

2024-12-12 15:16 UTC, ashalaenko commented on internal/store/query_utils.go
> +		if len(items) > int(opts.GetSize()-1) {
і чому GetSize саме int32 ?

2024-12-12 15:16 UTC, ashalaenko commented on internal/store/postgres/case.go
> +	res.Next = store.ResolvePaging(opts, res.Items)
чи правильно я розумію , що: 
- спочатку ми робимо запит без офсету-ліміту?
- потім ми вигрібаємо в scanCases весь результат з бази в память
- потім в ResolvePaging ми просто змінюємо (мутуємо вхідний аргумент) вибраний слайс
?

тобто  якщо по моєму запиту в базі є мільйон рядків, а я передав Size = 5, то воно вичитає мільйон рядків з бази в память , а потім мені поверне прсто три рядки?

2024-12-12 15:16 UTC, ashalaenko commented on internal/store/query_utils.go
> +
є пропозиція на даному етапі хочаб утілітні функції покривати тестами

2024-12-12 15:42 UTC, Dtsnko commented on internal/app/case.go
> +			//for _, item := range res.Items {
через те що в коментарях Володя забрав поле етаг, то нормалізувати там етаги нема як

2024-12-12 15:43 UTC, Dtsnko commented on internal/app/case.go
> +		if item.Reporter == nil {
маєш на увазі ось цю нормалізацію?

2024-12-12 15:51 UTC, Dtsnko commented on internal/store/query_utils.go
> +		if len(items) > int(opts.GetSize()-1) {
В прото ми маємо зазначати який саме це інт, інт64 буде завелике для визначення сторінки, тому обрали інт32, але можливо дійсно в конструкторі опцій варто його просто зразу конвертнути в звичайний інт

2024-12-13 10:30 UTC, Dtsnko commented on model/search.go
> +		Filter:  make(map[string]interface{}),
стрінг інтерфейс дає більше можливостей фільтрації в залежності який тип ми на поле засовуємо, тобто для кожного поля можна ще і різні типи засунути і в залежності від типу можна міняти логіку фільтрації

2024-12-16 08:51 UTC, ashalaenko commented on internal/store/postgres/case.go
> +	res.Next = store.ResolvePaging(opts, res.Items)
@Dtsnko  , для. мене це питання є найбільш основним, напевне : У нас лімітація йде на рівні бази чи на рівні коду ?

2024-12-16 12:34 UTC, merged