WTEL-5403
webitel/cases pull request #4
Opened 2024-12-26 13:48 UTC by Dtsnko

2024-12-26 13:49 UTC, Dtsnko commented on go.mod
> +)
Comment replace after pull request approve

2025-01-06 09:51 UTC, ashalaenko requested changes

2025-01-06 09:51 UTC, ashalaenko commented on internal/app/case_communication.go
> +	// TODO: RBAC check by request.CaseEtag
Це напевне треба обов'язково доробити

2025-01-06 09:51 UTC, ashalaenko commented on internal/app/case_communication.go
> +	if dbErr != nil {
Цю помилку краще залогувати і повернути на хттп 500

2025-01-06 09:51 UTC, ashalaenko commented on internal/app/case_communication.go
> +	// TODO: RBAC check by request.CaseEtag
знову ж RBAC

2025-01-06 09:51 UTC, ashalaenko commented on internal/app/case_communication.go
> +		return nil, dbErr
помилки, які в кінцевому вигляді для користувача перетворюються на 5хх треба логувати

2025-01-06 09:51 UTC, ashalaenko commented on internal/app/case_communication.go
> +	tag, err := etag.EtagOrId(etag.EtagCaseCommunication, request.Etag)
the same as above

2025-01-06 09:51 UTC, ashalaenko commented on internal/app/case_communication.go
> +		return nil, errors.NewBadRequestError("app.case_communication.unlink_communication.no_rows_affected", "No rows were affected while deleting")
я не впевнений , що потрібно повертати BadRequest : операція виконана успішно, операція семвнично корректна. Можемо повертати кількість видалених елементів, але тут буде або 1 або 0, тому частіше за все повертаються просто 200 ОК

2025-01-06 09:51 UTC, ashalaenko commented on internal/app/case_communication.go
> +	copy(fields, requestedFields)
тут напевне не потрібно копіювати слайс, якщо ти не плануєш змінювати єлементі слайсу

2025-01-06 09:51 UTC, ashalaenko commented on internal/app/case_timeline.go
> +		return nil, err
тут краще експлліцитно повертати помилку Bad Reques

2025-01-06 09:51 UTC, ashalaenko commented on internal/app/case_timeline.go
> +		return nil, err
також логування і відповідь 5хх

2025-01-06 09:51 UTC, ashalaenko commented on internal/app/case_timeline.go
> +func (c CaseTimelineService) GetTimeline(ctx context.Context, request *cases.GetTimelineRequest) (*cases.GetTimelineResponse, error) {
чи не потріібно нам тут перевіряти якщо не рбак то обак ?

2025-01-06 09:51 UTC, ashalaenko commented on internal/app/case_timeline.go
> +		if v := eventTypeCounter.DateFrom; v < dateFrom {
не розумію цю конструкцію . Чому просто не зробити : 
```
if eventTypeCounter.DateFrom < dateFrom {
   dateFrom = eventTypeCounter.DateFrom
}
```

2025-01-06 09:51 UTC, ashalaenko commented on internal/app/service_template.txt
> +// replace (CTRL + R) [MAIN_OBJECT] with your object name
забув запитати: де ми використсовуємо цей тепмплейт ?

2025-01-06 09:51 UTC, ashalaenko commented on internal/store/postgres/case_communication.go
> +	if len(res) == 0 && len(communications) != 0 {
тут цікаво : 
1. можливо перевірку на те що слайс communications не пустий винести в початок функції
2. коли у нас можливий `len(res) == 0 ` :  
    a. коли нам передали не валідний CommunicationId 
    b. коли у нас не має прав по рбак
    с. коли зв'язок уже є (ON CONFLICT DO NOTHING)
але все це бізнес логіка, і, на маю думку, хенделер має вирішувати помилка це чи не помилка. Тим паче, що дізнатися, що саме це за помилка поки не має можливості.

2025-01-06 09:51 UTC, ashalaenko commented on internal/store/postgres/case_communication.go
> +	if len(res) == 0 {
тут на мій погляд точно не потрібно повертати помилку. Максимум кількість видаленних рядків. тим паче, що ми приймаємо масив айді

2025-01-06 09:51 UTC, ashalaenko commented on internal/store/postgres/case_communication.go
> +	insertCte, args, err := store.FormAsCTE(delCte, delAlias)
тут мінор : у нас операція видалення , вище є змінна **delCte** , а тут **insertCte**

2025-01-06 09:51 UTC, ashalaenko commented on internal/store/postgres/case_communication.go
> +func ValidateCaseCommunicationCreate(input *cases.InputCaseCommunication) *dberr.DBError {
зараз це напевно не потрібно перероблювати, але з точку зору дизайну - це має бути на рівні хендлеру

2025-01-06 09:51 UTC, ashalaenko commented on internal/store/postgres/case_communication.go
> +			typeFound = true
1. тут тоді **break** також потрібен : нащо нам далі обходити мапу, якщо ми знайшли те, що шукали
2. в [Go 1.23](https://pkg.go.dev/maps@master#Keys) є можливвість отримати слайс ключів і зробити **slice.Contains** . Не впевнений , що це буде набагато краще, але така можливість є

2025-01-07 08:53 UTC, merged